[project]
name = "ekg"
version = "1.0.0"

git_repo_url = "https://github.com/vokegpu/ekg-ui-library/"
git_default_branch = "version-core"

[paths]
compile_commands = "cmake-build/compile_commands.json"

[pages]

homepage = "ekg-docs/readme.md"
paths = [
  "ekg-docs/model/*.md",
  "ekg-docs/tutorial/*.md"
]
